`July 19, 2022`

# Pandas: Series & DataFrame

- Library Pandas digunakan untuk memanipulasi data.
- Pandas dibangun dengan Numpy package sebagai basisnya.
- Data struktur pada Pandas disebut Series dan DataFrame.

**Series**

- Koleksi data seperti list dan array 1 dimensi, yang bisa menampung berbagai tipe data pada Python, bukan hanya data numerik saja.

- Yang membedakan Series dengan list dan array adalah Series memiliki nama atau label pada index-nya.


**DataFrame**

- Kumpulan dari Series yang memiliki index yang sama. 
- Bentuk DataFrame seperti tabel, dengan baris dan kolom, di mana tiap kolom berisi satu jenis variabel dan tiap baris berisi satu observasi.
- Misal: Nama, Umur, Gaji, Kota adalah contoh variabel (kolom) dan data dari tiap individu adalah isi barisnya.

In [1]:
# Import libraries
import numpy as np
import pandas as pd

## Create a Series

In [ ]:
my_list = [10, 20, 30]
my_array = np.array([10, 20, 30])
my_dict = {'A': 10, 'B': 20, 'C': 30}
label = 'Data1 Data2 Data3'.split()

In [ ]:
# Create a series from a list & array

print(pd.Series(my_list, index=label, 
    name='From List'))
print()
print(pd.Series(my_array, index=label, 
    name='From Array'))

Data1    10
Data2    20
Data3    30
Name: From List, dtype: int64

Data1    10
Data2    20
Data3    30
Name: From Array, dtype: int64


In [ ]:
# From dictionary
# Kalau dari dictionary, by default 
    # key akan menjadi index.
pd.Series(my_dict)

A    10
B    20
C    30
dtype: int64

In [ ]:
# Data type yang lain
labels = ['a', 'b', 'c']

x = pd.Series(data=labels)
x

0    a
1    b
2    c
dtype: object

In [ ]:
# If the index is default, the 
    # output would be RangeIndex
x.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
# Get the index of series
list(x.index)

[0, 1, 2]

In [ ]:
# Get the values of series
x.values

array(['a', 'b', 'c'], dtype=object)

In [ ]:
# Another example for custom index
labels = ['a', 'b', 'c']

y = pd.Series(data=labels, 
    index=['First', 'Second', 'Third'])
y

First     a
Second    b
Third     c
dtype: object

In [ ]:
y.index

Index(['First', 'Second', 'Third'], dtype='object')

In [ ]:
list(y.index)

['First', 'Second', 'Third']

In [ ]:
# Series juga dapat menampung functions
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

## Create a DataFrame

Ada 3 parameter yang harus dimasukkan saat membuat DataFrame:
1. Parameter data: Untuk memasukkan data yang ingin dimasukkan. Misal: berupa kumpulan list. Pastikan ukuran list-nya sama.
2. Parameter index: Untuk memberi nama atau label pada index-nya.
3. Parameter columns: Untuk memberi nama atau label pada kolom DataFrame.

*Pastikan jumlah nama index dan kolom sama dengan data yang dimasukkan.*

In [ ]:
# Create an array
my_array = np.random.randint(1, 16, 9)\
            .reshape(3, 3)

# Create a list
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8 , 9]

In [ ]:
# Create a DataFrame from an array
pd.DataFrame(my_array, columns='''Col1 Col2 
            Col3'''.split())

Col1  Col2  Col3
0    14     8    11
1     3     8     1
2    14    13    12

In [ ]:
# Create a DataFrame from a list
pd.DataFrame([list1, list2, list3], 
    columns='Col1 Col2 Col3'.split(), 
    index=[1, 2, 3])

Col1  Col2  Col3
1     1     2     3
2     4     5     6
3     7     8     9

In [ ]:
# Rename columns and indices 

# Cara 1
# Menggunakan split()
# Antar nama kolom dipisahkan spasi saja, 
    # dan dimasukkan ke dalam satu string
pd.DataFrame([list1, list2, list3], 
columns = 'kolom_1 kolom_2 kolom_3'.split(), 
index = 'index_1 index_2 index_3'.split()) 

kolom_1  kolom_2  kolom_3
index_1        1        2        3
index_2        4        5        6
index_3        7        8        9

In [ ]:
# Cara 2
# Memasukkan nama kolom dan index pada 
    # sebuah List
# Tidak perlu menggunakan split()
pd.DataFrame([list1, list2, list3], 
columns = ['kolom 1', 'kolom 2', 'kolom 3'], 
index = ['index_1', 'index_2', 'index_3']) 

kolom 1  kolom 2  kolom 3
index_1        1        2        3
index_2        4        5        6
index_3        7        8        9

In [ ]:
# Another example
a = [x for x in range(1, 5)]
b = [x for x in range(5, 9)]
c = [x for x in range(9, 13)]

# Dengan menggunakan cara ini, outputnya 
    # belum sesuai karena seharusnya tiap 
    # list menjadi 1 kolom yang sama
pd.DataFrame(data=[a, b, c],
             index=['a', 'b', 'c'],
             columns=['Col1', 'Col2', 
                        'Col3', 'Col4'])

Col1  Col2  Col3  Col4
a     1     2     3     4
b     5     6     7     8
c     9    10    11    12

In [ ]:
# Caranya adalah dengan menggunakan zip

a = [x for x in range(1, 5)]
b = [x for x in range(5, 9)]
c = [x for x in range(9, 13)]

pd.DataFrame(data=list(zip(a, b, c)),
        index=['a', 'b', 'c', 'd'],
    columns=['Col1', 'Col2', 'Col3'])

Col1  Col2  Col3
a     1     5     9
b     2     6    10
c     3     7    11
d     4     8    12

In [ ]:
# DataFrame juga bisa dibuat dari nested list.
new_list = [[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]]

# Tiap list akan menjadi 1 baris
pd.DataFrame(new_list,
            index='A B C'.split(),
            columns='W X Y Z'.split())

W   X   Y   Z
A  1   2   3   4
B  5   6   7   8
C  9  10  11  12

In [ ]:
# Mengubah tiap list menjadi 1 kolom
pd.DataFrame(new_list,
            index='A B C'.split(),
            columns='W X Y Z'.split()).T

A  B   C
W  1  5   9
X  2  6  10
Y  3  7  11
Z  4  8  12

In [ ]:
# Create a DataFrame from a dictionary
my_dict = {'A': [1, 2, 3, 4],
           'B': [5, 6, 7, 8],
           'C': [9, 10, 11, 12]}

# By default, nama kolom akan menggunakan 
    # nama key.
# Value dari tiap key akan menjadi 1 kolom 
    # yang sama.
pd.DataFrame(my_dict)

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

## Mini Exercise

In [2]:
# Buatlah sebuah DataFrame dengan isian seperti output di bawah ini.

# Cara 1
df = pd.DataFrame({'name': ['Resta', 'Vano', 'Marko', 'Tata', 'Yuri', 'Dina'],
                   'gender': 'Female Male Male Male Male Female'.split(),
                   'hired date': ['2016-12-04', '2018-04-13', '2018-07-04', '2016-11-18', '2017-05-26', '2015-03-20'],
                   'gross salary': [7000000, 7000000, 15000000, 12000000, 20000000, 15000000]},
                   index=['100111 100112 200210 200211 200312 300207'.split()])

df

name  gender  hired date  gross salary
100111  Resta  Female  2016-12-04       7000000
100112   Vano    Male  2018-04-13       7000000
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [3]:
# Cara 2: Mengggunakan list dan zip

# Definisikan dahulu datanya pada tiap variabel
name = ['Resta', 'Vano', 'Marko', 'Tata', 
        'Yuri', 'Dina']
gender = ['Female', 'Male', 'Male', 'Male', 
        'Male', 'Female']
hired_date = ['2016-12-04', '2018-04-13', '2018-07-04', 
            '2016-11-18', '2017-05-26', '2015-03-20']
gross_salary = [7000000, 7000000, 15000000, 12000000, 
                20000000, 15000000]
index = [100111, 100112, 200210, 200211, 
        200312, 300207]

# Menggunakan zip() untuk mengepak ulang tiap variabel
pd.DataFrame(list(zip(name, gender, hired_date, gross_salary)), 
            index=index, 
            columns=['name', 'gender', 'hire data', 
                    'gross salary'])

name  gender   hire data  gross salary
100111  Resta  Female  2016-12-04       7000000
100112   Vano    Male  2018-04-13       7000000
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [4]:
# Cara 3
# Hasilnya tidak akan sesuai dengan output. 
    # Harus di-transpose.
pd.DataFrame([name, gender, hired_date, gross_salary], 
            columns=index, 
            index=['name', 'gender', 'hire data', 
                    'gross salary'])

100111      100112      200210      200211      200312  \
name               Resta        Vano       Marko        Tata        Yuri   
gender            Female        Male        Male        Male        Male   
hire data     2016-12-04  2018-04-13  2018-07-04  2016-11-18  2017-05-26   
gross salary     7000000     7000000    15000000    12000000    20000000   

                  300207  
name                Dina  
gender            Female  
hire data     2015-03-20  
gross salary    15000000

In [5]:
# Transpose DataFrame
pd.DataFrame([name, gender, hired_date, gross_salary], 
            columns=index, 
            index=['name', 'gender', 'hire data', 
                    'gross salary']).T

name  gender   hire data gross salary
100111  Resta  Female  2016-12-04      7000000
100112   Vano    Male  2018-04-13      7000000
200210  Marko    Male  2018-07-04     15000000
200211   Tata    Male  2016-11-18     12000000
200312   Yuri    Male  2017-05-26     20000000
300207   Dina  Female  2015-03-20     15000000

## Indexing & Selection

Kita juga bisa melakukan indexing pada DataFrame untuk memilih data tertentu, seperti halnya pada list dan array. 


- Untuk memilih data di dalam DataFrame, index pertama yang harus ditulis adalah nama kolom.
- Misalnya, kita ingin memilih kolom pertama di df yang bernama 'name', maka jalankan df['name'], bukan df[0].
- Penulisan nama kolom harus tepat, karena case sensitive.

- Selanjutnya, di kolom 'name' ini kita ingin menampilkan baris pertama saja, maka tuliskan posisi elemen sesuai index baris.
- Jalankan df['name'][0] untuk menampilkan baris pertama pada kolom W.
- Jika ingin menampilkan lebih dari satu baris, lakukan start:stop:step pada index kedua. 
- Jalankan df ['name'][0:2] untuk menampilkan nilai pertama dan kedua pada kolom name.
Tipe data dari output akan terlihat berupa Pandas Series. 


In [6]:
df

name  gender  hired date  gross salary
100111  Resta  Female  2016-12-04       7000000
100112   Vano    Male  2018-04-13       7000000
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [7]:
# Indexing menggunakan nama kolom
df['name']

100111    Resta
100112     Vano
200210    Marko
200211     Tata
200312     Yuri
300207     Dina
Name: name, dtype: object

In [8]:
df['name'][0:2]

100111    Resta
100112     Vano
Name: name, dtype: object

In [9]:
# Indexing lebih dari satu kolom, 
    # perhatikan jumlah kurung siku.
# Kurung siku harus berjumlah 2 jika 
    # ingin memanggil data lebih dari 1 kolom.
# Output-nya akan berupa DataFrame

df[['name', 'gender']]

name  gender
100111  Resta  Female
100112   Vano    Male
200210  Marko    Male
200211   Tata    Male
200312   Yuri    Male
300207   Dina  Female

In [10]:
# Indexing dari kolom nama dan baris 
    # index pertama. 
# Output yang akan ditampilkan berarti nama 
    # orang berdasarkan nomor index 
    # yang dimasukkan.
df['name']['100112']

'Vano'

In [11]:
df['name'][1]

'Vano'

In [12]:
# Jumlah data bisa lebih dari 1, 
    # perhatikan jumlah kurung siku
df['name'][['100111', '100112']]

100111    Resta
100112     Vano
Name: name, dtype: object

In [16]:
df['name'][[0, 3]]

100111    Resta
200211     Tata
Name: name, dtype: object

Selain menggunakan kurung siku, mengakses suatu kolom pada DataFrame dapat menggunakan tanda titik (attribute access).

Misal, jika ingin menampilkan kolom 'name', maka kodenya adalah df.name

Namun, metode ini tidak direkomendasikan, karena jika nama kolomnya kebetulan sama dengan nama atribut atau fungsi dalam Pandas, maka outputnya tidak akan sesuai.

In [17]:
# Mengakses data menggunakan titik 
    # tidak terlalu disarankan
df.name

100111    Resta
100112     Vano
200210    Marko
200211     Tata
200312     Yuri
300207     Dina
Name: name, dtype: object

In [18]:
df['sum'] = [1, 2, 3, 4, 5, 6]
df

name  gender  hired date  gross salary  sum
100111  Resta  Female  2016-12-04       7000000    1
100112   Vano    Male  2018-04-13       7000000    2
200210  Marko    Male  2018-07-04      15000000    3
200211   Tata    Male  2016-11-18      12000000    4
200312   Yuri    Male  2017-05-26      20000000    5
300207   Dina  Female  2015-03-20      15000000    6

In [19]:
df['sum']

100111    1
100112    2
200210    3
200211    4
200312    5
300207    6
Name: sum, dtype: int64

In [20]:
# Akses kolom 'sum' dengan metode attribute access
# Return value tidak sesuai dengan yang diinginkan 
    # ketika nama kolom sama dengan nama built-in function
df.sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of          name  gender  hired date  gross salary  sum
100111  Resta  Female  2016-12-04       7000000    1
100112   Vano    Male  2018-04-13       7000000    2
200210  Marko    Male  2018-07-04      15000000    3
200211   Tata    Male  2016-11-18      12000000    4
200312   Yuri    Male  2017-05-26      20000000    5
300207   Dina  Female  2015-03-20      15000000    6>

In [ ]:
# Contoh lain jika nama kolom mengandung space
# Error karena menyalahi aturan syntax Python
df.hired date

SyntaxError: ignored

In [ ]:
# Bandingkan dengan metode kurung siku
df['hired date']

100111    2016-12-04
100112    2018-04-13
200210    2018-07-04
200211    2016-11-18
200312    2017-05-26
300207    2015-03-20
Name: hired date, dtype: object

### loc & iloc

**loc**

Bagaimana jika kita ingin menampilkan data bukan berdasarkan kolom, tetapi berdasarkan index-nya? 

- Label based.
- Gunakan .loc untuk menampilkan data berdasarkan index-nya. 
- Misalnya, data dengan index yang sudah custom, seperti index '100111' ingin ditampilkan, maka jalankan df.loc['100111']. 
Hasilnya berupa series bernama A berisi data di baris A dan nama kolom sebagai index-nya.
<br><br>
- Kita juga bisa melakukan slicing menggunakan .loc. 
- Misalnya data di baris 100111 sampai 200210 ingin ditampilkan, maka jalankan df.loc['100111': '200210']. 
- df.loc['100111': '200210'] bukan berarti dimulai dari baris '100111' dan berhenti pada baris '200210'. Baris '200210' juga ikut ditampilkan karena stop pada loc slicing bersifat inclusive.
<br><br>
- Perhatikan, tidak seperti fungsi pada umumnya, fungsi .loc menggunakan kurung siku. 

In [21]:
# loc

df.loc['100111']

name  gender  hired date  gross salary  sum
100111  Resta  Female  2016-12-04       7000000    1

In [22]:
# Slicing pada .loc, stop bersifat inclusive.
df.loc['100111': '200210']

name  gender  hired date  gross salary  sum
100111  Resta  Female  2016-12-04       7000000    1
100112   Vano    Male  2018-04-13       7000000    2
200210  Marko    Male  2018-07-04      15000000    3

In [23]:
df[['name', 'gross salary']].loc['200210']

name  gross salary
200210  Marko      15000000

In [24]:
# Subset of data

# Cara 1
df.loc[['100111', '200210'], 
    ['name', 'gross salary']]

name  gross salary
100111  Resta       7000000
200210  Marko      15000000

In [25]:
# Cara 2
df[['name', 'gross salary']]\
    .loc[['100111', '200210']]

name  gross salary
100111  Resta       7000000
200210  Marko      15000000

In [ ]:
# Error karena index tidak dengan default value. Solusinya adalah menggunakan iloc
df[['name', 'gross salary']].loc[[1, 2]]

KeyError: ignored

In [26]:
df[['name', 'gross salary']].iloc[[1, 2]]

name  gross salary
100112   Vano       7000000
200210  Marko      15000000

In [27]:
df.loc[['200210', '200211']]

name gender  hired date  gross salary  sum
200210  Marko   Male  2018-07-04      15000000    3
200211   Tata   Male  2016-11-18      12000000    4

**iloc**

- Pada .iloc, kita memakai nomor posisi index dan bukan nama index seperti pada .loc.
- Seperti indexing pada umumnya, nomor posisi index pada Pandas juga dimulai dari 0. 
<br><br>
- Misalkan, baris '100111' ingin ditampilkan, maka jalankan df.iloc[0]. 
- Hasilnya berupa pandas series bernama '100111' berisi nilai di baris '100111' dengan nama kolom sebagai index-nya. 
<br><br>
- Rangkaian start: stop: step bisa digunakan saat indexing dengan .iloc.
- df.iloc[0:4:2] artinya menampilkan data dari baris 0 sampai sebelum baris 4 dan memiliki jarak 2 antar baris (stop bersifat exclusive).
- Hasilnya dapat kita lihat, yaitu dataframe berisi baris '100111', atau baris di index 0, dan baris '200210' atau baris di index 2.


In [ ]:
# Mengakses data baris pertama dengan 
    # menggunakan .iloc

df.iloc[0]

name            Raven Bierman
gender                 Female
hired date         2016-12-04
gross salary          7000000
sum                         1
Name: (100111,), dtype: object

In [28]:
df.drop(columns='sum', axis=1, inplace=True)

In [29]:
# Menggunakan start: stop: step untuk 
    # slicing baris data
# Pada iloc, stop bersifat exclusive.
df.iloc[0:3]

name  gender  hired date  gross salary
100111  Resta  Female  2016-12-04       7000000
100112   Vano    Male  2018-04-13       7000000
200210  Marko    Male  2018-07-04      15000000

In [30]:
df.iloc[0:2, [0, 3]] # Fancy indexing pada akses kolom

name  gross salary
100111  Resta       7000000
100112   Vano       7000000

In [31]:
df.iloc[0, 3]

7000000

In [32]:
df

name  gender  hired date  gross salary
100111  Resta  Female  2016-12-04       7000000
100112   Vano    Male  2018-04-13       7000000
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [34]:
# Perhatikan jumlah kurung siku saat indexing.
# Seperti fancy indexing, berarti menampilkan 
    # data index ke 2 dan 5 dari semua kolom.
df.iloc[[2, 5]]

name  gender  hired date  gross salary
200210  Marko    Male  2018-07-04      15000000
300207   Dina  Female  2015-03-20      15000000

Jika index bernilai default, maka akses index untuk loc dan iloc dapat menggunakan cara yang sama dan akan mengembalikan hasil yang sama.

In [35]:
# Create a copy of df
df_new = df.copy()
df_new = df.reset_index(drop=True)
df_new

name  gender  hired date  gross salary
0  Resta  Female  2016-12-04       7000000
1   Vano    Male  2018-04-13       7000000
2  Marko    Male  2018-07-04      15000000
3   Tata    Male  2016-11-18      12000000
4   Yuri    Male  2017-05-26      20000000
5   Dina  Female  2015-03-20      15000000

In [36]:
# Indexing index 1 dan 2 mengggunakan loc
df_new.loc[[1, 2]]

name gender  hired date  gross salary
1   Vano   Male  2018-04-13       7000000
2  Marko   Male  2018-07-04      15000000

In [37]:
# Indexing index 1 dan 2 mengggunakan iloc
df_new.iloc[[1, 2]]

name gender  hired date  gross salary
1   Vano   Male  2018-04-13       7000000
2  Marko   Male  2018-07-04      15000000

## Conditional Selection

- Conditional selection pada Pandas mirip di Numpy array. 
- Ketika kita memberikan syarat pada DataFrame, maka Pandas akan mengecek apakah tiap-tiap data pada DataFrame memenuhi syarat tersebut.
<br><br>
- Misalnya df['gross salary'] > 10000000, maka hasilnya berisi True dan False.
- True berarti data memenuhi syarat lebih besar dari 10000000 dan False tidak memenuhi syarat.


- Slice: endpoint is excluded from iloc result, but included in loc.
- Conditions: loc accepts boolean Series, but iloc can only accept a boolean list.

In [38]:
df

name  gender  hired date  gross salary
100111  Resta  Female  2016-12-04       7000000
100112   Vano    Male  2018-04-13       7000000
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [39]:
df[df['gross salary'] > 10000000]

name  gender  hired date  gross salary
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [40]:
df['gross salary'] > 10000000

100111    False
100112    False
200210     True
200211     True
200312     True
300207     True
Name: gross salary, dtype: bool

In [41]:
# Bisa juga dengan ditampung terlebih 
    # dahulu ke dalam variable.
higher_gross = df['gross salary'] > 10000000

df[higher_gross]

name  gender  hired date  gross salary
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [42]:
df[df['gross salary'] > 10000000]['name']

200210    Marko
200211     Tata
200312     Yuri
300207     Dina
Name: name, dtype: object

In [43]:
df[df['gross salary'] > 10000000][['name']]

name
200210  Marko
200211   Tata
200312   Yuri
300207   Dina

In [45]:
list(df['gross salary'] > 10000000)

[False, False, True, True, True, True]

In [ ]:
# Error karena iloc by default tidak dapat 
    # menerima boolean series, hanya dapat 
    # menerima boolean list/array.
df.iloc[(df['gross salary'] > 10000000)]

ValueError: ignored

In [46]:
# Convert ke list untuk iloc agar 
    # terbaca sebagai boolean list
df.iloc[list(df['gross salary'] > 10000000)]

name  gender  hired date  gross salary
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [47]:
df.loc[(df['gross salary'] > 10000000)]

name  gender  hired date  gross salary
200210  Marko    Male  2018-07-04      15000000
200211   Tata    Male  2016-11-18      12000000
200312   Yuri    Male  2017-05-26      20000000
300207   Dina  Female  2015-03-20      15000000

In [48]:
# Memasukkan lebih dari satu kondisi
# AND --> &
# OR --> |

# Syntax --> df[() | () | () | ()]
    # Tiap kondisi diapit dengan ()

# Menampilkan data di df yang memiliki 
    # gross salary > 10000000 dan gender male
df[(df['gross salary'] > 10000000) & 
    (df['gender'] == 'Male')]

name gender  hired date  gross salary
200210  Marko   Male  2018-07-04      15000000
200211   Tata   Male  2016-11-18      12000000
200312   Yuri   Male  2017-05-26      20000000

In [49]:
# Cara lain menggunakan loc
df.loc[(df['gross salary'] > 10000000) & 
    (df['gender'] == 'Male')]

name gender  hired date  gross salary
200210  Marko   Male  2018-07-04      15000000
200211   Tata   Male  2016-11-18      12000000
200312   Yuri   Male  2017-05-26      20000000

**Callable Function**

In [ ]:
# loc & iloc dapat menerima callable function, 
    # tapi terbatas hanya untuk satu argumen saja.
df.loc[:, lambda df: ['name', 'gender']]

name  gender
100111    Raven Bierman  Female
100112    Valter Havers    Male
200210    Marko Mendell    Male
200211  Takahiro Momota    Male
200312  Yahiko Tilemans    Male
300207     Dina Rebaine  Female

In [ ]:
df.loc[:, ['name', 'gender']]

name  gender
100111    Raven Bierman  Female
100112    Valter Havers    Male
200210    Marko Mendell    Male
200211  Takahiro Momota    Male
200312  Yahiko Tilemans    Male
300207     Dina Rebaine  Female

In [ ]:
# Filter data using loc
df.loc[lambda df: df['gender'] == 'Female']

name  gender  hired date  gross salary  sum
100111  Raven Bierman  Female  2016-12-04       7000000    1
300207   Dina Rebaine  Female  2015-03-20      15000000    6

In [ ]:
# Filter data using iloc
df.iloc[lambda df: list(df['gender'] == 'Female')]

name  gender  hired date  gross salary  sum
100111  Raven Bierman  Female  2016-12-04       7000000    1
300207   Dina Rebaine  Female  2015-03-20      15000000    6

## Summary

**loc merupakan label based dan input-nya berupa:**

- Sebuah label, contoh: 'A' atau 3 (3 diinterpretasikan sebagai label sebuah index).
- List of labels, contoh: ['A', 'B', 'C'] atau [1, 2, 3] (1, 2,3 diinterpretasikan sebagai label index).
- Slicing dari labels, contoh: 'A': 'C' (output berupa A, B, C karena end point bersifat inclusive).
- Conditions, dapat menerima boolean Series atau boolean list/array.
- Dapat menerima callable function dengan hanya satu argumen.

**iloc merupakan integer position based dan input-nya berupa:**

- Sebuah integer, contoh: 3.
- List atau array berisi integers, contoh: [1, 2, 3].
- Slicing dengan integers, contoh: 1:7 (end point 7 bersifat exclusive).
- Conditions, hanya dapat menerima boolean list/array.
- Dapat menerima callable function dengan hanya satu argumen.

**loc dan iloc dapat memiliki fungsi yang sama ketika index atau kolom dari DataFrame adalah 0-based integers.**

____

# Pandas Manipulation

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Membuat DataFrame
np.random.seed(1)

df = pd.DataFrame(data=np.random.randint(10, 
    100, (5, 4)), columns='A B C D'.split())
df

A   B   C   D
0  47  22  82  19
1  85  15  89  74
2  26  11  86  81
3  16  35  60  30
4  28  94  21  38

## Adding Data

**Membuat baris baru**

In [ ]:
# Membuat baris baru (menggunakan .loc)
# Pada baris, jika kita menambahkan data baru berupa 
    # angka yang berbeda tipe, maka jika kita 
    # tambahkan float, integer pun akan 
    # berubah menjadi float.

df.loc['New row'] = [1, 2, 3, 4]
df

A   B   C   D
0        47  22  82  19
1        85  15  89  74
2        26  11  86  81
3        16  35  60  30
4        28  94  21  38
New row   1   2   3   4

**Membuat kolom baru**

In [ ]:
# Pada kolom, tipe angka tidak akan berubah 
    # meskipun kita memiliki integer dan float.
df['E'] = [1.2, 2.2, 3.2, 4.4, 5.3, 6.1]
df

A   B   C   D    E
0        47  22  82  19  1.2
1        85  15  89  74  2.2
2        26  11  86  81  3.2
3        16  35  60  30  4.4
4        28  94  21  38  5.3
New row   1   2   3   4  6.1

In [ ]:
# Menyelipkan kolom baru pada index 
    # tertentu menggunakan .insert()

df.insert(2, 'New col', [10, 20, 30, 40, 50, 60])
df

A   B  New col   C   D    E
0        47  22       10  82  19  1.2
1        85  15       20  89  74  2.2
2        26  11       30  86  81  3.2
3        16  35       40  60  30  4.4
4        28  94       50  21  38  5.3
New row   1   2       60   3   4  6.1

## Removing Data

**Menghapus Kolom**

In [ ]:
# Hapus kolom hanya pada cell ini (tidak permanen)
# .drop() sifatnya tidak inplace/permanen
# Kolom --> axis = 1

df.drop('New col', axis=1)

A   B   C   D    E
0        47  22  82  19  1.2
1        85  15  89  74  2.2
2        26  11  86  81  3.2
3        16  35  60  30  4.4
4        28  94  21  38  5.3
New row   1   2   3   4  6.1

In [ ]:
# Jika ingin menghapus secara permanen, 
    # gunakan inplace = True atau timpa ke variabel.

# Cara 1
df.drop('New col', axis=1, inplace=True)
df

In [ ]:
# Cara 2
df = df.drop('E', axis=1)
df

A   B   C   D
0        47  22  82  19
1        85  15  89  74
2        26  11  86  81
3        16  35  60  30
4        28  94  21  38
New row   1   2   3   4

**Menghapus Baris**

In [ ]:
# Hapus baris 'New row' secara tidak permanen
# Baris --> axis = 0

df.drop('New row', axis=0)

A   B   C   D
0  47  22  82  19
1  85  15  89  74
2  26  11  86  81
3  16  35  60  30
4  28  94  21  38

In [ ]:
# Hapus secara permanen
df.drop('New row', axis=0, inplace=True)
df

A   B   C   D
0  47  22  82  19
1  85  15  89  74
2  26  11  86  81
3  16  35  60  30
4  28  94  21  38

## Index & Multi-Index

In [ ]:
# Mengubah index dengan kolom tertentu 
    # menggunakan set_index()
df_new = df.copy()
df_new.set_index('A', inplace=True)
df_new

B   C   D
A             
47  22  82  19
85  15  89  74
26  11  86  81
16  35  60  30
28  94  21  38

In [ ]:
# Mengembalikan index ke nilai default 
    # menggunakan reset_index()
df_new.reset_index(inplace=True)
df_new

A   B   C   D
0  47  22  82  19
1  85  15  89  74
2  26  11  86  81
3  16  35  60  30
4  28  94  21  38

In [ ]:
# Mengganti nama kolom
df_new.rename(columns={'A':'X'}, inplace=True)
df_new

X   B   C   D
0  47  22  82  19
1  85  15  89  74
2  26  11  86  81
3  16  35  60  30
4  28  94  21  38

**Multi-Index**

In [ ]:
outside = ['Jakarta', 'Jakarta', 'Jakarta', 
            'Bandung', 'Bandung', 'Bandung']
inside = [1, 2, 3, 1, 2, 3]

hier_index = list(zip(outside, inside))
hier_index

[('Jakarta', 1),
 ('Jakarta', 2),
 ('Jakarta', 3),
 ('Bandung', 1),
 ('Bandung', 2),
 ('Bandung', 3)]

In [ ]:
# Buat jadi multi-index
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('Jakarta', 1),
            ('Jakarta', 2),
            ('Jakarta', 3),
            ('Bandung', 1),
            ('Bandung', 2),
            ('Bandung', 3)],
           )

In [ ]:
# Buat array 6x2 untuk mengisi DataFrame
np.random.seed(1)
values = np.random.randint(10, 100, (6, 2))
values

array([[47, 22],
       [82, 19],
       [85, 15],
       [89, 74],
       [26, 11],
       [86, 81]])

In [ ]:
# Buat DataFrame multi-index
df = pd.DataFrame(values,
index=hier_index,
columns=['Restaurant A', 'Restaurant B']
                  )

df

Restaurant A  Restaurant B
Jakarta 1            47            22
        2            82            19
        3            85            15
Bandung 1            89            74
        2            26            11
        3            86            81

In [ ]:
type(hier_index)

pandas.core.indexes.multi.MultiIndex

In [ ]:
# Indexing kolom
df[['Restaurant A']]

Restaurant A
Jakarta 1            47
        2            82
        3            85
Bandung 1            89
        2            26
        3            86

In [ ]:
df.loc[:, ['Restaurant A']]

Restaurant A
Jakarta 1            47
        2            82
        3            85
Bandung 1            89
        2            26
        3            86

In [ ]:
# Indexing baris
df.loc['Jakarta']

Restaurant A  Restaurant B
1            47            22
2            82            19
3            85            15

In [ ]:
df.iloc[0:3]

Restaurant A  Restaurant B
Jakarta 1            47            22
        2            82            19
        3            85            15

In [ ]:
df.loc['Jakarta'].loc[2]

Restaurant A    82
Restaurant B    19
Name: 2, dtype: int64

In [ ]:
# Indexing dengan menggunakan .xs 
    # atau cross-section
# Lebih mudah daripada .loc untuk mengakses 
    # data yang memiliki multi index

# Indexing baris 'Jakarta', lalu indexing 
    # lagi baris 2 'Location' di baris Jakarta.
df.xs(('Jakarta', 2))

Restaurant A    82
Restaurant B    19
Name: (Jakarta, 2), dtype: int64

In [ ]:
# Memanggil nama index baris
df.index.names

FrozenList([None, None])

In [ ]:
# Memberikan nama untuk tiap index
df.index.names = ['City', 'Location']
df

Restaurant A  Restaurant B
City    Location                            
Jakarta 1                   47            22
        2                   82            19
        3                   85            15
Bandung 1                   89            74
        2                   26            11
        3                   86            81

In [ ]:
# Indexing location 3 untuk tiap city
df.xs(3, level='Location')

Restaurant A  Restaurant B
City                               
Jakarta            85            15
Bandung            86            81

## Sorting

Sifatnya tidak permanen. 

Jika ingin permanen, tambahkan parameter **inplace=True**

In [ ]:
df.reset_index(inplace=True)
df

City  Location  Restaurant A  Restaurant B
0  Jakarta         1            47            22
1  Jakarta         2            82            19
2  Jakarta         3            85            15
3  Bandung         1            89            74
4  Bandung         2            26            11
5  Bandung         3            86            81

In [ ]:
df.set_index('City', inplace=True)
df

Location  Restaurant A  Restaurant B
City                                         
Jakarta         1            47            22
Jakarta         2            82            19
Jakarta         3            85            15
Bandung         1            89            74
Bandung         2            26            11
Bandung         3            86            81

In [ ]:
# By default, ascending = True
df.sort_values('Restaurant A')

Location  Restaurant A  Restaurant B
City                                         
Bandung         2            26            11
Jakarta         1            47            22
Jakarta         2            82            19
Jakarta         3            85            15
Bandung         3            86            81
Bandung         1            89            74

In [ ]:
df.sort_values('Restaurant A', ascending=False)

Location  Restaurant A  Restaurant B
City                                         
Bandung         1            89            74
Bandung         3            86            81
Jakarta         3            85            15
Jakarta         2            82            19
Jakarta         1            47            22
Bandung         2            26            11

In [ ]:
# Mengurutkan berdasarkan lebih dari 1 kolom
df.sort_values(by=['Restaurant A', 'Restaurant B'])

Location  Restaurant A  Restaurant B
City                                         
Bandung         2            26            11
Jakarta         1            47            22
Jakarta         2            82            19
Jakarta         3            85            15
Bandung         3            86            81
Bandung         1            89            74

In [ ]:
# Mengurutkan berdasarkan index
df.sort_index()

Location  Restaurant A  Restaurant B
City                                         
Bandung         1            89            74
Bandung         2            26            11
Bandung         3            86            81
Jakarta         1            47            22
Jakarta         2            82            19
Jakarta         3            85            15

Location  Restaurant A  Restaurant B
City                                         
Jakarta         1            47            22
Jakarta         2            82            19
Jakarta         3            85            15
Bandung         1            89            74
Bandung         2            26            11
Bandung         3            86            81

# Pandas Functionality

Explore DataFrame

- .head()
- .tail()
- .info()
- .shape
- .columns
- .dtypes

Descriptive Statistics
- .describe()
- .min(), .max(), .mean(), .mode(), .median(), .std()
- unique(), nunique(), value_counts()

In [ ]:
# Load dataset untuk file .csv
df = pd.read_csv('Salaries.csv')
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [ ]:
# Menampilkan 10 baris awal pada dataset
# df.head() default-nya adalah 5 baris awal, 
    # namun jumlah baris yang ingin 
    # ditampilkan bisa kita atur.
df.head(10)

Id        EmployeeName                                        JobTitle  \
0   1      NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2        GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3      ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4   CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5     PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5   6      DAVID SULLIVAN                       ASSISTANT DEPUTY CHIEF II   
6   7           ALSON LEE              BATTALION CHIEF, (FIRE DEPARTMENT)   
7   8       DAVID KUSHNER                  DEPUTY DIRECTOR OF INVESTMENTS   
8   9      MICHAEL MORRIS              BATTALION CHIEF, (FIRE DEPARTMENT)   
9  10  JOANNE HAYES-WHITE          CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   
5  118602.00      8601.00  189082.74       NaN  316285.74         316285.74   
6   92492.01     89062.90  134426.14       NaN  315981.05         315981.05   
7  256576.96         0.00   51322.50       NaN  307899.46         307899.46   
8  176932.64     86362.68   40132.23       NaN  303427.55         303427.55   
9  285262.00         0.00   17115.73       NaN  302377.73         302377.73   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN  
5  2011    NaN  San Francisco     NaN  
6  2011    NaN  San Francisco     NaN  
7  2011    NaN  San Francisco     NaN  
8  2011    NaN  San Francisco     NaN  
9  2011    NaN  San Francisco     NaN

In [ ]:
# Mengecek 5 baris terakhir pada dataset
df.tail()

Id   EmployeeName                    JobTitle  BasePay  \
148649  148650  Roy I Tillery                   Custodian      0.0   
148650  148651   Not provided                Not provided      NaN   
148651  148652   Not provided                Not provided      NaN   
148652  148653   Not provided                Not provided      NaN   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148649          0.0      0.00       0.0      0.00              0.00  2014   
148650          NaN       NaN       NaN      0.00              0.00  2014   
148651          NaN       NaN       NaN      0.00              0.00  2014   
148652          NaN       NaN       NaN      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes         Agency  Status  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN

In [ ]:
# Menampilkan informasi semua kolom
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
# Mengecek jumlah missing value pada tiap kolom
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [ ]:
# Melihat ukuran DataFrame (baris, kolom)
df.shape

(148654, 13)

In [ ]:
# Mengecek semua nama kolom
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [ ]:
# Mengecek tipe data tiap kolom
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object

**Descriptive Statistics**

In [ ]:
# Default-nya akan mengembalikan informasi 
    # kolom numerikal saja
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [ ]:
# Mengecek informasi kolom object/string
df.describe(include='object')

EmployeeName          JobTitle         Agency
count        148654            148654         148654
unique       110811              2159              1
top       Kevin Lee  Transit Operator  San Francisco
freq             13              7036         148654

In [ ]:
# Mengecek informasi stats deksriptif semua 
    # kolom secara sekaligus.
df.describe(include='all')

Id EmployeeName          JobTitle        BasePay  \
count   148654.000000       148654            148654  148045.000000   
unique            NaN       110811              2159            NaN   
top               NaN    Kevin Lee  Transit Operator            NaN   
freq              NaN           13              7036            NaN   
mean     74327.500000          NaN               NaN   66325.448841   
std      42912.857795          NaN               NaN   42764.635495   
min          1.000000          NaN               NaN    -166.010000   
25%      37164.250000          NaN               NaN   33588.200000   
50%      74327.500000          NaN               NaN   65007.450000   
75%     111490.750000          NaN               NaN   94691.050000   
max     148654.000000          NaN               NaN  319275.010000   

          OvertimePay       OtherPay       Benefits       TotalPay  \
count   148650.000000  148650.000000  112491.000000  148654.000000   
unique            NaN            NaN            NaN            NaN   
top               NaN            NaN            NaN            NaN   
freq              NaN            NaN            NaN            NaN   
mean      5066.059886    3648.767297   25007.893151   74768.321972   
std      11454.380559    8056.601866   15402.215858   50517.005274   
min         -0.010000   -7058.590000     -33.890000    -618.130000   
25%          0.000000       0.000000   11535.395000   36168.995000   
50%          0.000000     811.270000   28628.620000   71426.610000   
75%       4658.175000    4236.065000   35566.855000  105839.135000   
max     245131.880000  400184.250000   96570.660000  567595.430000   

        TotalPayBenefits           Year  Notes         Agency  Status  
count      148654.000000  148654.000000    0.0         148654     0.0  
unique               NaN            NaN    NaN              1     NaN  
top                  NaN            NaN    NaN  San Francisco     NaN  
freq                 NaN            NaN    NaN         148654     NaN  
mean        93692.554811    2012.522643    NaN            NaN     NaN  
std         62793.533483       1.117538    NaN            NaN     NaN  
min          -618.130000    2011.000000    NaN            NaN     NaN  
25%         44065.650000    2012.000000    NaN            NaN     NaN  
50%         92404.090000    2013.000000    NaN            NaN     NaN  
75%        132876.450000    2014.000000    NaN            NaN     NaN  
max        567595.430000    2014.000000    NaN            NaN     NaN

**Kolom Numerikal**

In [ ]:
# Mean (rata-rata) suatu kolom
df['BasePay'].mean()

66325.44884050643

In [ ]:
# Median (nilai tengah)
df['BasePay'].median()

65007.45

In [ ]:
# Nilai yang paling sering muncul 
    # di suatu kolom
df['BasePay'].mode()

0    0.0
dtype: float64

In [ ]:
# Nilai minimum
df['BasePay'].min()

-166.01

In [ ]:
# Nilai maksimum
df['BasePay'].max()

319275.01

In [ ]:
# Standard deviation
df['BasePay'].std()

42764.63549525958

In [ ]:
# Sum
df['BasePay'].sum()

9819151073.590002

In [ ]:
# Count
df['BasePay'].count()

148045

**Kolom Kategorikal**

In [ ]:
# Nilai yang paling sering muncul
df['JobTitle'].mode()

0    Transit Operator
dtype: object

In [ ]:
# Menampilkan nilai unique value pada suatu kolom
df['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [ ]:
# Menampilkan jumlah unique value pada suatu kolom
df['JobTitle'].nunique()

2159

In [ ]:
# Menghitung frekuensi dari tiap unique value pada suatu kolom
df['JobTitle'].value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
CHIEF HOUSING INSPECTOR                              1
TRAFFIC SIGNAL OPERATOR                              1
COURT COMPUTER FACILITIES COORDINATOR                1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
VICTIM & WITNESS TECHNICIAN                          1
Name: JobTitle, Length: 2159, dtype: int64

In [ ]:
# Menghitung frekuensi percentage
df['JobTitle'].value_counts(normalize=True)

In [ ]:
# Menampilkan 10 job title dengan frekuensi terbanyak
df['JobTitle'].value_counts().head(10)

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Custodian                       2418
TRANSIT OPERATOR                2388
Firefighter                     2359
Recreation Leader               1971
Patient Care Assistant          1945
Name: JobTitle, dtype: int64

## Missing Value

- Missing value adalah data kosong di kolom tertentu di baris tertentu.
- Bisa disebabkan karena kesalahan dalam pengambilan data atau karena memang datanya tidak tersedia.

In [ ]:
df_num = pd.DataFrame({
    'A': [1, 2, np.nan, 10],
    'B': [5, np.nan, np.nan, 11],
    'C': [7, 8 , 9, 12]
})

df_num

A     B   C
0   1.0   5.0   7
1   2.0   NaN   8
2   NaN   NaN   9
3  10.0  11.0  12

In [ ]:
df_num.isna()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False
3  False  False  False

In [ ]:
# isna dan isnull sama saja
df_num.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [ ]:
# Sifat default-nya tidak inplace
# Default-nya axis = 1
df_num.dropna()

A     B   C
0   1.0   5.0   7
3  10.0  11.0  12

In [ ]:
df_num

A     B   C
0   1.0   5.0   7
1   2.0   NaN   8
2   NaN   NaN   9
3  10.0  11.0  12

In [ ]:
# Menghapus baris yang memiliki missing value
# Define axis = 0
df_num.dropna(axis=0)

A     B   C
0   1.0   5.0   7
3  10.0  11.0  12

In [ ]:
# Threshold berarti jumlah minimal data 
    # yang tidak berupa missing value.
# Kalau thresh = 2, berarti hanya baris 
    # yang memiliki minimal 2 data poin 
    # yang tidak bernilai NaN yang tidak
    # akan didrop.
# By default, thresh axis-nya adalah 0 .

df_num.dropna(thresh=2)

A     B   C
0   1.0   5.0   7
1   2.0   NaN   8
3  10.0  11.0  12

In [ ]:
# Dalam 1 kolom, minimal ada 3 data terisi 
    # (bukan missing value)
df_num.dropna(thresh=3, axis=1)

A   C
0   1.0   7
1   2.0   8
2   NaN   9
3  10.0  12

In [ ]:
# Mengisi missing value dengan teks 'Unknown'
# By default, sifatnya tidak inplace/permanen
df_num.fillna(value='Unknown')

A        B   C
0      1.0      5.0   7
1      2.0  Unknown   8
2  Unknown  Unknown   9
3     10.0     11.0  12

In [ ]:
df_num['A'].fillna(df_num['A'].mean())

0     1.000000
1     2.000000
2     4.333333
3    10.000000
Name: A, dtype: float64

In [ ]:
# Kalau ingin permanen, tambahkan inplace=True
df_num['A'].fillna(df_num['A'].mean(), 
inplace=True)

In [ ]:
df_num

A     B   C
0   1.000000   5.0   7
1   2.000000   NaN   8
2   4.333333   NaN   9
3  10.000000  11.0  12

## Data Aggregation

In [ ]:
# Kolom 'Year' terdiri dari 4 kategori
df['Year'].value_counts(ascending=True)

2011    36159
2012    36766
2013    37606
2014    38123
Name: Year, dtype: int64

In [ ]:
# Mengelompokkan data berdasarkan kolom 'Year'
df.groupby('Year')

In [ ]:
# Melakukan agregasi berdasarkan kolom 'Year'
df.groupby('Year').mean()

Id       BasePay  OvertimePay     OtherPay      Benefits  \
Year                                                                   
2011   18080.0  63595.956517  4531.065429  3617.081926           NaN   
2012   54542.5  65436.406857  5023.417824  3653.437583  26439.966967   
2013   91728.5  69630.030216  5281.641980  3819.969007  23829.076572   
2014  129593.0  66564.421924  5401.993737  3505.421251  24789.601756   

          TotalPay  TotalPayBenefits  Notes  Status  
Year                                                 
2011  71744.103871      71744.103871    NaN     NaN  
2012  74113.262265     100553.229232    NaN     NaN  
2013  77611.443142     101440.519714    NaN     NaN  
2014  75463.918140     100250.918884    NaN     NaN

In [ ]:
# Rata-rata BasePay & OtherPay berdasarkan tahun
df.groupby('Year').mean()[['BasePay', 'OtherPay']]

BasePay     OtherPay
Year                           
2011  63595.956517  3617.081926
2012  65436.406857  3653.437583
2013  69630.030216  3819.969007
2014  66564.421924  3505.421251

In [ ]:
# Grouping lebih dari 1 kolom
df.groupby(['Year', 'JobTitle']).mean()
[['BasePay', 'OtherPay']]

BasePay      OtherPay
Year JobTitle                                                  
2011 ACCOUNT CLERK                   43300.806506    361.656988
     ACCOUNTANT                      46643.172000    786.096000
     ACCOUNTANT INTERN               28732.663958    274.648333
     ACUPUNCTURIST                   66374.400000   1220.000000
     ADMINISTRATIVE ANALYST          63435.628602    519.238925
...                                           ...           ...
2014 Wire Rope Cable Maint Sprv      93904.720000  17497.330000
     Worker's Comp Supervisor 1      54505.333333   2184.113333
     Worker's Compensation Adjuster  69915.985385    720.470000
     X-Ray Laboratory Aide           45490.340286   1190.456857
     Youth Comm Advisor              32417.420000   4048.490000

[4137 rows x 2 columns]

In [ ]:
# Rata-rata TotalPay pada tahun 2012
df.groupby('Year').mean()[['TotalPay']].loc[2012]

TotalPay    74113.262265
Name: 2012, dtype: float64

In [ ]:
# Membuat kolom baru dari penjumlahan 2 kolom lainnya
df['TotalBenefits'] = df['BasePay'] + df['OtherPay']
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  TotalBenefits  
0  2011    NaN  San Francisco     NaN      567595.43  
1  2011    NaN  San Francisco     NaN      293777.40  
2  2011    NaN  San Francisco     NaN      229191.73  
3  2011    NaN  San Francisco     NaN      276222.90  
4  2011    NaN  San Francisco     NaN      316636.19

In [ ]:
# Transpose
df.describe().T

count          mean           std      min        25%  \
Id                148654.0  74327.500000  42912.857795     1.00  37164.250   
BasePay           148045.0  66325.448841  42764.635495  -166.01  33588.200   
OvertimePay       148650.0   5066.059886  11454.380559    -0.01      0.000   
OtherPay          148650.0   3648.767297   8056.601866 -7058.59      0.000   
Benefits          112491.0  25007.893151  15402.215858   -33.89  11535.395   
TotalPay          148654.0  74768.321972  50517.005274  -618.13  36168.995   
TotalPayBenefits  148654.0  93692.554811  62793.533483  -618.13  44065.650   
Year              148654.0   2012.522643      1.117538  2011.00   2012.000   
Notes                  0.0           NaN           NaN      NaN        NaN   
Status                 0.0           NaN           NaN      NaN        NaN   
TotalBenefits     148045.0  69971.110248  45706.207733  -618.13  35693.150   

                       50%         75%        max  
Id                74327.50  111490.750  148654.00  
BasePay           65007.45   94691.050  319275.01  
OvertimePay           0.00    4658.175  245131.88  
OtherPay            811.27    4236.065  400184.25  
Benefits          28628.62   35566.855   96570.66  
TotalPay          71426.61  105839.135  567595.43  
TotalPayBenefits  92404.09  132876.450  567595.43  
Year               2013.00    2014.000    2014.00  
Notes                  NaN         NaN        NaN  
Status                 NaN         NaN        NaN  
TotalBenefits     67193.44   99131.820  567595.43

In [ ]:
# Menampilkan descriptive statistics suatu kolom
df.describe().T.loc['Benefits']

count    112491.000000
mean      25007.893151
std       15402.215858
min         -33.890000
25%       11535.395000
50%       28628.620000
75%       35566.855000
max       96570.660000
Name: Benefits, dtype: float64